### ISSUE TITLE
Change name of Daisy programmer to Daisy Web Programmer

### ISSUE THREAD

**Issue by andrewikenberry** [electro-smith/Programmer#26]
Change name of Daisy programmer to (Daisy Web Programmer) everywhere it appears on programmer page. (USB Programmer, Usb Programmer, Daisy Programmer, etc. )

**Comment by andrewikenberry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change name of Daisy programmer to (Daisy Web Programmer) everywhere it appears on programmer page. (USB Programmer, Usb Programmer, Daisy Programmer, etc. )](https://trello.com/c/GZgTDPe8/64-change-name-of-daisy-programmer-to-daisy-web-programmer-everywhere-it-appears-on-programmer-page-usb-programmer-usb-programmer-d)

**Comment by stephenhensley** [comment]
handled in latest PR #27
