### ISSUE TITLE
Does not recognize or offer relevant board and uploads

### ISSUE THREAD

**Issue by ri0t** [electro-smith/Programmer#31]
Just plugged in a very brand new Daisy Patch's Seed and it only offered to patch Pod's SimpleLed app after circumventing #16.
Shouldn't it offer Daisy Patch as platform along with the relevant apps?

Will probably try uploading something locally built tomorrow, but haven't come around to set up the toolchain yet. Wanted the rack working first. (Yes, this is my third module, and the first capable of producing audio/cv).

Would be happy to get pointed at ready-made firmware images that i can drop in the programmer, too!

Norns will live next to the Daisy, btw.

**Comment by stephenhensley** [comment]
@ri0t this should be fixed along with the issues you mentioned on Daisy Examples (this app grabs the examples, and the platform information from that repo's dist/ folder. So if something there breaks, it breaks here).

We've updated the CI to fail more loudly. So if any things like that happen in the future, we'll be able to fix them immediately.

Thanks for reporting the issue!
